# Generated by Django 5.2.8 on 2025-11-13 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('reports_to', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('severity', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField()),
                ('status', models.CharField(max_length=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alerts.employee')),
            ],
            options={
                'ordering': ['-created_at', 'id'],
            },
        ),
    ]
